### ISSUE TITLE
translation.properties

### ISSUE THREAD

**Issue by SHypoleac** [ravignir/RekMOD#182]
Hello, i want to translate this mod into polish language, but i don't know what exactly should i put there. This English.properties looks a bit old, and some translations have 6000 lines, when others only 1600. Can you put here some schema? btw is this english.properties is even is use? :D

**Comment by SeventhM** [comment]
Please read [here](https://yairm210.github.io/Unciv/Other/Translating/), notably the section for "Translation generation - for modders". I could probably provide an updated English.properties, But admittedly, it's fairly low on the list of priorities for me, and it should still be possible to translate using the method stated in that link unless you're only on android

**Comment by SHypoleac** [comment]
I have already translated the entire basic version of the game and it would be useful to update this file to include only the necessary elements. Maybe it's not a priority for you, but I'm personally disgusted by these German names and propably im not exeption. So can you tell me how looks like your priorities now? :)

**Comment by SeventhM** [comment]
> and it would be useful to update this file to include only the necessary elements

Again, in the link I provided above, there is a very simple method to getting such a file. Provide a translation of an item, open the game, go to options, press the "advanced" tab, and press "generate translations file". If you're on mobile, this process doesn't work, but otherwise, this should be a straightforwards method that isn't that big a deal


> So can you tell me how looks like your priorities now?

I'm torn between irl concerns, making updates to Unciv itself, and I have an edit to Deciv I've been working on. Outside of Unciv or irl concerns, I've been working on updating an old keyboard I've used for a while, and I'm heavily involved in the community of another game (Polytopia). Editing a file that I don't necessarily need updating is very, very low on my list of priorities, pretty much regardless of the situation. Though, since I'm already looking at Rekmod right now, I guess I could update it all. Please check #185 

> but I'm personally disgusted by these German names and propably im not exeption

I gave no clue what you're referring to

**Comment by SHypoleac** [comment]
> Again, in the link I provided above, there is a very simple method to getting such a file. Provide a translation of an item, open the game, go to options, press the "advanced" tab, and press "generate translations file".
oh, thanks, but for now i have it only as android game, so it could be nice if you accept this request :)

**Comment by SeventhM** [comment]
#186

**Comment by SHypoleac** [comment]
[Spanish_info.txt](https://github.com/ravignir/RekMOD/files/14998221/Spanish_info.txt)
[Chinese_info.txt](https://github.com/ravignir/RekMOD/files/14998218/Chinese_info.txt)
[Korean_info.txt](https://github.com/ravignir/RekMOD/files/14998220/Korean_info.txt)

**Comment by SeventhM** [comment]
> using deepl

Thinking on it, I'm going to reject any of these translations that aren't to your native language unless someone else comes and backs up your translation. The Polish translation is one thing (there was literally no translation there), but I'm not nearly as comfortable allowing machine translations into other languages, and aren't really comfortable if you say the polish translation was machine translated

If you wish to use your translations locally or from your fork, that's fine. I'm closing this issue and your PR, however
